export const ROUTE_PATHS = {
  discovery: '/',
  docs: '/docs',
  swaggerJson: '/docs/swagger.json',
  llmsTxt: '/llms.txt',
  mcp: '/mcp',
  authMe: '/auth/me',
  authLogout: '/auth/logout',
  usersMe: '/users/me',
  usersMeAgentDrafts: '/users/me/agent-drafts',
  agentDrafts: '/agent-drafts',
  agentDraftById: '/agent-drafts/{draftId}',
  agentDraftProvisionWallet: '/agent-drafts/{draftId}/provision-wallet',
  agentDraftLaunch: '/agent-drafts/{draftId}/launch',
  vaults: '/vaults',
  vaultById: '/vaults/{id}',
  vaultTokens: '/vaults/{id}/tokens',
  tokens: '/tokens',
  prices: '/prices',
  pricesRefresh: '/prices/refresh',
  agentById: '/agents/{agentId}',
  agentByOwner: '/agents/by-owner/{owner}',
  agentByErc8004: '/agents/by-erc8004/{erc8004AgentId}',
  agentLinkErc8004: '/agents/{agentId}/erc8004/link',
  agentRegister: '/agents/register',
  agentRegisterQuote: '/agents/register/quote',
  agentTradeIntents: '/agents/{agentId}/trade-intents',
  agentTradeIntentsQuote: '/agents/{agentId}/trade-intents/quote',
  agentTrades: '/agents/{agentId}/trades',
  agentPositions: '/agents/{agentId}/positions',
  agentClosedPositions: '/agents/{agentId}/closed-positions',
  agentPositionById: '/agents/{agentId}/positions/{positionId}',
  agentAddIntents: '/agents/{agentId}/add-intents',
  agentAddIntentsQuote: '/agents/{agentId}/add-intents/quote',
  agentReduceIntents: '/agents/{agentId}/reduce-intents',
  agentReduceIntentsQuote: '/agents/{agentId}/reduce-intents/quote',
  agentExitLadderIntents: '/agents/{agentId}/exit-ladder-intents',
  agentExitLadderIntentsQuote: '/agents/{agentId}/exit-ladder-intents/quote',
  agentRiskState: '/agents/{agentId}/risk-state',
  transactionByHash: '/transactions/{txHash}',
} as const

export const HTTP_ROUTES = {
  agentRegister: `POST ${ROUTE_PATHS.agentRegister}`,
} as const
