// Generated by scripts/generate-subgraph-networks.mjs — do not edit.
import { Address, dataSource } from '@graphprotocol/graph-ts'

const ARBITRUM_ONE_LENS = Address.fromString('0xB9acd4CeB37FF72260aE2f3721f19D602d07d02C')
const ARBITRUM_ONE_ROUTER = Address.fromString('0xb78f0EAdAF1D6209D73a3C5eb8203f0cb3a6ccba')
const ARBITRUM_SEPOLIA_LENS = Address.fromString('0x62272B653a128e2d5786Ae63C063157dfD3aa2bE')
const ARBITRUM_SEPOLIA_ROUTER = Address.fromString('0xADaf3a37fFDC10447356E131DC316509c44885D2')

export function tradeRouterLensAddress(): Address {
  const network = dataSource.network()
  if (network == "arbitrum-sepolia") {
    return ARBITRUM_SEPOLIA_LENS
  }
  return ARBITRUM_ONE_LENS
}

export function tradeRouterAddress(): Address {
  const network = dataSource.network()
  if (network == "arbitrum-sepolia") {
    return ARBITRUM_SEPOLIA_ROUTER
  }
  return ARBITRUM_ONE_ROUTER
}
